on:
  workflow_dispatch:
  schedule:
    # run every 48 hours
    - cron: '20 */48 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        SKIP_UPDATED: '1'
